language: java

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE goals_test;'
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
- wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /tmp
- chmod ugo+rx /tmp/chromedriver
- export CHROME_BIN=chromium-browser
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

env:
- CHROME_DRIVER_PATH=/tmp/chromedriver

script:
- cat /etc/*release*
- ./gradlew check --info --stacktrace

dist: trusty
addons:
  chrome: stable
