dist: xenial
sudo: required
addons:
  mariadb: '10.0'
  apt:
    packages:
      - openjdk-8-jdk
jdk: openjdk8

before_install:
  - echo "create database goals_test;" | mysql -u root
  - echo "create database goals;" | mysql -u root
  - echo "show databases;" | mysql -u root
  - echo "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION;" | mysql -u root

script:
  - ./gradlew check --info --stacktrace

