language: java

services:
  - mysql

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
- cat /etc/*release*
- ./gradlew check --info --stacktrace