language: java

services:
  - mysql

sudo: required

before_install:
  - mysql -e 'CREATE DATABASE goals_test;'
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - echo PATH=$PATH

before_script:
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
- wget http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/bin
- chmod ugo+rx /home/travis/bin/chromedriver

script:
- cat /etc/*release*
- ./gradlew check --info --stacktrace

dist: xenial

addons:
  chrome: stable
